services:
  db:
    image: mysql:9.2
    container_name: mysql
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: changemeinprod!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  db_data: